# Generated by Django 5.1.3 on 2024-12-09 09:38

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_users_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to=users.models.get_random_filename),
        ),
    ]
